name: VideoApp CI & Performance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours

jobs:
  run-tests:
    name: Run Unit + Performance Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pytest httpx

    - name: Configure environment variables
      run: echo "VIDEO_API_URL=https://videoapp-esbxhscadcg8d8bc.uksouth-01.azurewebsites.net/videos" >> $GITHUB_ENV

    - name: Run unit tests
      run: |
        python -m pytest tests/ --maxfail=1 --disable-warnings

    - name: Run performance test
      run: |
        python performance_test.py

    - name: Configure environment variables
      run: |
        echo "VIDEO_API_URL=https://videoapp-esbxhscadcg8d8bc.uksouth-01.azurewebsites.net/videos" >> $GITHUB_ENV
        echo "AZURE_STORAGE_CONNECTION_STRING=${{ vars.AZURE_STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV
        echo "AZURE_CONTAINER_NAME=${{ vars.AZURE_CONTAINER_NAME }}" >> $GITHUB_ENV
        echo "COSMOS_ENDPOINT=${{ vars.COSMOS_ENDPOINT }}" >> $GITHUB_ENV
        echo "COSMOS_KEY=${{ vars.COSMOS_KEY }}" >> $GITHUB_ENV
        echo "COSMOS_DATABASE=${{ vars.COSMOS_DATABASE }}" >> $GITHUB_ENV
        echo "COSMOS_USERS_CONTAINER=${{ vars.COSMOS_USERS_CONTAINER }}" >> $GITHUB_ENV
        echo "COSMOS_VIDEOS_CONTAINER=${{ vars.COSMOS_VIDEOS_CONTAINER }}" >> $GITHUB_ENV
        echo "COSMOS_COMMENTS_CONTAINER=${{ vars.COSMOS_COMMENTS_CONTAINER }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ vars.SECRET_KEY }}" >> $GITHUB_ENV
  